# Generated by Django 5.1.2 on 2024-11-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_attribute'),
        ('products', '0005_productattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
