# Generated by Django 5.1.2 on 2024-11-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_attributevalue'),
        ('products', '0006_product_attribute_product_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
            ],
        ),
    ]
